#!/usr/bin/env python3
"""Bind 8,805 local scalar vegetation placements to the offline authored pack."""

from __future__ import annotations

import argparse
from collections import Counter
import hashlib
import json
import math
import os
from pathlib import Path
import re
import sys


HERE = Path(__file__).resolve().parent
CATALOG_PATH = HERE / "prototype_catalog.json"
SAFE_ID = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def safe_relative(root: Path, raw: str, label: str) -> Path:
    require(isinstance(raw, str) and raw and "\\" not in raw and "%" not in raw, f"{label} is unsafe")
    parts = Path(raw).parts
    require(not Path(raw).is_absolute() and all(part not in {"", ".", ".."} for part in parts), f"{label} traverses")
    resolved = (root / raw).resolve()
    require(resolved.is_relative_to(root), f"{label} escapes the pack root")
    return resolved


def write_new(path: Path, payload: bytes) -> None:
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644)
    with os.fdopen(descriptor, "wb") as handle:
        handle.write(payload)
        handle.flush()
        os.fsync(handle.fileno())


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build the offline placement-to-authored-asset index.")
    parser.add_argument("--pack-root", type=Path, required=True)
    parser.add_argument("--vegetation", type=Path, action="append", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--receipt", type=Path, required=True)
    args = parser.parse_args(argv)
    args.pack_root = args.pack_root.expanduser().resolve()
    args.output = args.output.expanduser().resolve()
    args.receipt = args.receipt.expanduser().resolve()
    args.vegetation = [path.expanduser().resolve() for path in args.vegetation]
    require(args.pack_root.is_dir() and not args.pack_root.is_symlink(), "--pack-root must be a regular directory")
    require(len(args.vegetation) == 2, "exact Customs indexing requires exactly two vegetation tile files")
    require(args.output.parent == args.pack_root and args.receipt.parent == args.pack_root, "index and receipt must sit at pack root")
    require(args.output.suffix.lower() == ".json" and args.receipt.suffix.lower() == ".json", "outputs must be JSON")
    require(args.output != args.receipt, "index and receipt paths must differ")
    require(not args.output.exists() and not args.receipt.exists(), "index outputs are no-clobber")
    return args


def load_catalog() -> tuple[dict, dict[str, dict]]:
    document = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    prototypes = document.get("prototypes")
    require(document.get("schemaVersion") == 1, "catalog schema changed")
    require(isinstance(prototypes, list) and len(prototypes) == 31, "catalog must contain 31 prototypes")
    by_name = {entry.get("name"): entry for entry in prototypes}
    require(len(by_name) == 31 and None not in by_name, "catalog names are invalid")
    return document, by_name


def generated_assets(pack_root: Path, catalog_by_name: dict[str, dict]) -> tuple[list[dict], dict[str, dict]]:
    manifest_path = pack_root / "generation-manifest.json"
    require(manifest_path.is_file() and not manifest_path.is_symlink(), "generation-manifest.json is missing")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    require(manifest.get("schemaVersion") == 1 and manifest.get("map") == "customs", "generation manifest schema changed")
    records = manifest.get("records")
    require(isinstance(records, list) and len(records) == 93, "generation manifest must contain 93 records")
    grouped: dict[str, list[dict]] = {}
    for record in records:
        name = record.get("prototype")
        require(name in catalog_by_name, f"unknown generated prototype {name!r}")
        lod = record.get("lod")
        require(lod in (0, 1, 2), f"invalid generated LOD for {name}")
        glb = safe_relative(pack_root, record.get("glb"), f"{name} LOD{lod} glb")
        receipt = safe_relative(pack_root, record.get("receipt"), f"{name} LOD{lod} receipt")
        require(glb.is_file() and receipt.is_file(), f"generated files are missing for {name} LOD{lod}")
        require(glb.stat().st_size == record.get("bytes"), f"generated byte count changed for {name} LOD{lod}")
        require(f"sha256:{sha256_file(glb)}" == record.get("sha256"), f"generated hash changed for {name} LOD{lod}")
        grouped.setdefault(name, []).append(record)

    assets = []
    by_name = {}
    for name in sorted(catalog_by_name, key=str.lower):
        spec = catalog_by_name[name]
        lods = sorted(grouped.get(name, []), key=lambda record: record["lod"])
        require([record["lod"] for record in lods] == [0, 1, 2], f"{name} does not have exactly LOD0/1/2")
        seeds = {record.get("seed") for record in lods}
        require(len(seeds) == 1 and all(isinstance(seed, int) for seed in seeds), f"{name} seed set is invalid")
        asset = {
            "assetId": f"customs.vegetation.{name.lower()}",
            "prototypeName": name,
            "family": spec["family"],
            "form": spec["form"],
            "dry": spec["dry"],
            "seed": next(iter(seeds)),
            "gltf": {"unit": "metre", "upAxis": "+y", "forwardAxis": "+z", "pivot": "base-center"},
            "collision": "none",
            "geometryEvidence": "original approximation from scalar prototype identity and fallback envelope",
            "lods": [{
                "lod": record["lod"],
                "file": record["glb"],
                "sha256": record["sha256"],
                "bytes": record["bytes"],
                "triangles": record["triangles"],
                "textureResolution": record["textureResolution"],
            } for record in lods],
        }
        assets.append(asset)
        by_name[name] = asset
    require(len(assets) == 31, "authored asset index must contain 31 assets")
    return assets, by_name


def scalar_tile(path: Path) -> tuple[dict, dict]:
    require(path.is_file() and not path.is_symlink(), f"vegetation source is not a regular file: {path.name}")
    require(path.stat().st_size <= 32 * 1024 * 1024, f"vegetation source is too large: {path.name}")
    document = json.loads(path.read_text(encoding="utf-8"))
    require(isinstance(document, dict), f"vegetation source must be an object: {path.name}")
    require(document.get("map") == "customs", f"vegetation map changed in {path.name}")
    require(document.get("localOnly") is True, f"vegetation source is not local-only: {path.name}")
    require(document.get("sourceFrame") == "eft-unity-world-metres-y-up", f"source frame changed in {path.name}")
    tile_id = document.get("tileId")
    require(isinstance(tile_id, str) and SAFE_ID.fullmatch(tile_id), f"tile ID is unsafe in {path.name}")
    prototypes = document.get("prototypes")
    instances = document.get("instances")
    require(isinstance(prototypes, list) and isinstance(instances, list), f"prototype/instance arrays missing in {path.name}")
    by_id = {}
    indexes = set()
    for position, prototype in enumerate(prototypes):
        require(isinstance(prototype, dict), f"prototype {position} is invalid in {path.name}")
        prototype_id = prototype.get("id")
        name = prototype.get("name")
        index = prototype.get("index")
        require(isinstance(prototype_id, str) and SAFE_ID.fullmatch(prototype_id), f"unsafe prototype ID in {path.name}")
        require(isinstance(name, str) and name, f"prototype name is invalid in {path.name}")
        require(isinstance(index, int) and index >= 0 and index not in indexes, f"prototype index is invalid in {path.name}")
        require(prototype_id not in by_id, f"duplicate prototype ID in {path.name}")
        by_id[prototype_id] = {"id": prototype_id, "name": name, "index": index}
        indexes.add(index)

    instance_indexes = set()
    normalized_instances = []
    for position, instance in enumerate(instances):
        require(isinstance(instance, dict), f"instance {position} is invalid in {path.name}")
        index = instance.get("index")
        prototype_id = instance.get("prototypeId")
        require(isinstance(index, int) and index >= 0 and index not in instance_indexes, f"instance index is invalid in {path.name}")
        require(prototype_id in by_id, f"instance {index} references unknown prototype in {path.name}")
        # Validate scalar finiteness without copying coordinates into the pack index.
        for vector_key in ("positionNormalized", "worldPosition"):
            vector = instance.get(vector_key)
            require(isinstance(vector, dict) and set(vector) == {"x", "y", "z"}, f"{vector_key} shape changed in {path.name}")
            require(all(
                not isinstance(value, bool) and isinstance(value, (int, float)) and math.isfinite(value)
                for value in vector.values()
            ), f"{vector_key} is non-finite in {path.name}")
        normalized_instances.append({"index": index, "prototypeId": prototype_id})
        instance_indexes.add(index)
    normalized_instances.sort(key=lambda value: value["index"])
    return {
        "tileId": tile_id,
        "prototypes": sorted(by_id.values(), key=lambda value: value["index"]),
        "instances": normalized_instances,
    }, {
        "file": path.name,
        "bytes": path.stat().st_size,
        "sha256": f"sha256:{sha256_file(path)}",
        "prototypeCount": len(prototypes),
        "instanceCount": len(instances),
    }


def main() -> None:
    args = parse_args(sys.argv[1:])
    catalog, catalog_by_name = load_catalog()
    assets, assets_by_name = generated_assets(args.pack_root, catalog_by_name)
    tiles = []
    source_receipts = []
    for source in args.vegetation:
        tile, receipt = scalar_tile(source)
        tiles.append(tile)
        source_receipts.append(receipt)
    tiles.sort(key=lambda value: value["tileId"])
    source_receipts.sort(key=lambda value: value["file"])
    require(len({tile["tileId"] for tile in tiles}) == 2, "vegetation tile IDs are duplicated")

    bindings = []
    placements = []
    counts = Counter()
    ordinal = 0
    for tile in tiles:
        prototype_by_id = {prototype["id"]: prototype for prototype in tile["prototypes"]}
        for prototype in tile["prototypes"]:
            asset = assets_by_name.get(prototype["name"])
            require(asset is not None, f"no authored asset for scalar prototype {prototype['name']}")
            bindings.append({
                "tileId": tile["tileId"],
                "prototypeId": prototype["id"],
                "prototypeIndex": prototype["index"],
                "prototypeName": prototype["name"],
                "assetId": asset["assetId"],
            })
        for instance in tile["instances"]:
            prototype = prototype_by_id[instance["prototypeId"]]
            asset = assets_by_name[prototype["name"]]
            placements.append({
                "placementOrdinal": ordinal,
                "tileId": tile["tileId"],
                "instanceIndex": instance["index"],
                "prototypeId": prototype["id"],
                "assetId": asset["assetId"],
            })
            counts[prototype["name"]] += 1
            ordinal += 1

    expected_counts = Counter({entry["name"]: entry["instances"] for entry in catalog["prototypes"]})
    require(counts == expected_counts, "placement-to-prototype counts do not match the reviewed 8,805 ledger")
    require(len(placements) == 8805, "pack index must map exactly 8,805 placements")
    require(len(bindings) == 58, "pack index must bind the reviewed 58 tile-local prototype IDs")

    index = {
        "schemaVersion": 1,
        "documentType": "tarkovzero-customs-offline-vegetation-pack-index",
        "map": "customs",
        "status": "offline-production-draft-not-live",
        "sourceFrame": "eft-unity-world-metres-y-up",
        "runtimeFrame": "three-z-up-metres",
        "runtimeFromSource": "[-x, -z, y]",
        "counts": {
            "authoredAssets": len(assets),
            "lodFiles": len(assets) * 3,
            "tilePrototypeBindings": len(bindings),
            "placements": len(placements),
        },
        "sourceReceipts": source_receipts,
        "authoredAssets": assets,
        "prototypeBindings": bindings,
        "placements": placements,
        "runtimeContract": {
            "exactScalarPlacement": True,
            "fixedDisplayReliefOwnedByRuntime": True,
            "collision": "none",
            "geometry": "original approximation; not source-game topology or measured source-mesh bounds",
            "livePromotion": False,
        },
    }
    index_payload = (json.dumps(index, indent=2, sort_keys=True, ensure_ascii=True) + "\n").encode("utf-8")
    write_new(args.output, index_payload)
    receipt = {
        "schemaVersion": 1,
        "documentType": "tarkovzero-customs-offline-vegetation-pack-index-receipt",
        "indexFile": args.output.name,
        "bytes": len(index_payload),
        "sha256": f"sha256:{hashlib.sha256(index_payload).hexdigest()}",
        "builderSha256": f"sha256:{sha256_file(Path(__file__).resolve())}",
        "catalogSha256": f"sha256:{sha256_file(CATALOG_PATH)}",
        "generationManifestSha256": f"sha256:{sha256_file(args.pack_root / 'generation-manifest.json')}",
        "counts": index["counts"],
        "copyrightBoundary": {
            "coordinatesCopiedIntoIndex": False,
            "gameMeshesIncluded": False,
            "gameTexturesIncluded": False,
            "geometryApproximation": True,
            "collisionIncluded": False,
        },
    }
    try:
        write_new(args.receipt, (json.dumps(receipt, indent=2, sort_keys=True) + "\n").encode("utf-8"))
    except Exception:
        if args.output.exists() and sha256_file(args.output) == hashlib.sha256(index_payload).hexdigest():
            args.output.unlink()
        raise
    print(json.dumps({
        "index": str(args.output),
        "receipt": str(args.receipt),
        "placements": len(placements),
        "prototypeBindings": len(bindings),
        "authoredAssets": len(assets),
        "sha256": receipt["sha256"],
    }, indent=2, sort_keys=True))


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"vegetation pack index failed: {error}", file=sys.stderr)
        raise SystemExit(1) from error
